name: mh4518
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - colorama=0.4.6
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.16.1
  - jedi=0.19.1
  - jupyter_client=8.5.0
  - jupyter_core=5.4.0
  - libffi=3.4.4
  - libsodium=1.0.18
  - llvmlite=0.41.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.5.8
  - numba=0.58.0
  - numexpr=2.8.7
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.11
  - packaging=23.2
  - pandas=2.1.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3
  - platformdirs=3.11.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pywin32=305
  - pyzmq=25.1.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.12.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.8
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.43.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.1
      - nelson-siegel-svensson==0.5.0
      - pillow==10.1.0
      - pyparsing==3.1.1
      - scipy==1.11.3
